"""initial schema

Revision ID: 9764a18aa922
Revises: 
Create Date: 2026-02-16 18:17:42.837782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9764a18aa922'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('sub_industry', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('daily_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_company_date')
    )
    op.create_index(op.f('ix_daily_prices_company_id'), 'daily_prices', ['company_id'], unique=False)
    op.create_index(op.f('ix_daily_prices_date'), 'daily_prices', ['date'], unique=False)
    op.create_table('earnings_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('call_date', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('transcript_source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'fiscal_quarter', name='uq_call_quarter')
    )
    op.create_index(op.f('ix_earnings_calls_company_id'), 'earnings_calls', ['company_id'], unique=False)
    op.create_table('post_earnings_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('earnings_call_id', sa.Integer(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('pre_close', sa.Float(), nullable=True),
    sa.Column('post_close', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=True),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('realized_volatility', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['earnings_call_id'], ['earnings_calls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('earnings_call_id', 'window_days', name='uq_metric_window')
    )
    op.create_index(op.f('ix_post_earnings_metrics_earnings_call_id'), 'post_earnings_metrics', ['earnings_call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_earnings_metrics_earnings_call_id'), table_name='post_earnings_metrics')
    op.drop_table('post_earnings_metrics')
    op.drop_index(op.f('ix_earnings_calls_company_id'), table_name='earnings_calls')
    op.drop_table('earnings_calls')
    op.drop_index(op.f('ix_daily_prices_date'), table_name='daily_prices')
    op.drop_index(op.f('ix_daily_prices_company_id'), table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
