"""add fundamentals table

Revision ID: a3fb1691548e
Revises: 9764a18aa922
Create Date: 2026-03-06 11:06:31.181473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3fb1691548e'
down_revision: Union[str, None] = '9764a18aa922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('statement_type', sa.String(length=32), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('operating_income', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('diluted_eps', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('cash_and_equivalents', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('operating_cash_flow', sa.Float(), nullable=True),
    sa.Column('investing_cash_flow', sa.Float(), nullable=True),
    sa.Column('financing_cash_flow', sa.Float(), nullable=True),
    sa.Column('free_cash_flow', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'statement_type', 'period_date', 'period', name='uq_fundamental')
    )
    op.create_index(op.f('ix_fundamentals_company_id'), 'fundamentals', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fundamentals_company_id'), table_name='fundamentals')
    op.drop_table('fundamentals')
    # ### end Alembic commands ###
